CREATE TABLE IF NOT EXISTS user_role (
  id      BIGSERIAL NOT NULL PRIMARY KEY,
  user_id BIGINT    NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  role_id BIGINT    NOT NULL REFERENCES role (id) ON DELETE CASCADE
);